# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wIPvLNeXpsrZe7dV82aEZ3sq_SQbB_j
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer ,util
model=SentenceTransformer('all-MiniLM-L6-V2')
text1=input("Enter text 1: ")
text2=input("Enter text 2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity= util.cos_sim(embedding1,embedding2)
print("\nsimilarity score:",round(float(similarity),2))
if similarity > 0.75:
  print(" similarity level: High")
elif similarity > 0.4:
  print(" similarity level: Medium")
else:
  print(" similarity level: Low")