# -*- coding: utf-8 -*-
"""Text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m5Vslr_zripK61Er4em66PIn8BDIxcp
"""

!pip install transformers

from transformers import pipeline
notes_generator=pipeline("text-generation",model="Tgpt2")
chapter = input("enter chapter name:")
prompt_notes=f"""
write detailed study notes for the chapter {chapter}
include explaination ,examples,and key points.
"""
detailed_notes=notes_generator(prompt_notes,max_length=300,num_return_sequences=1)
print("\n Detailed Notes : \n")
print(detailed_notes[0]['generated_text'])
prompt_summary=f"""
summarize the chapter {chapter} into one page
make it simple and exam_oriented.
"""
summary=notes_generator(prompt_summary,max_length=200,num_return_sequences=1)
print("\n one page summary : \n")
print(summary[0]['generated_text'])
prompt_definitions=f"""
list importantdefinitions and formulas from the chapter
{chapter}
use bullet points
"""